# -*- coding: utf-8 -*-
"""Python Tips and Tricks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mU5zRaN5faLZSuMMKufkLVyyRxTVK9aN
"""

condition = True

if condition:
  x = 1
else:
  x = 0
print(x)

# Using Ternary Conditionals

x = 1 if condition else 0
print(x)

# Underscore Placeholders for large numbers

num1 = 10000000000
num2 = 100000000
Total1 = num3 + num4
print("Total1 = ",Total1)

# underscore won't affect the programm anyway
num3 = 10_000_000_000
num4 = 100_000_000

Total2 = num1 + num2
print("Total2 = ",Total2)

# To add commas in output use f string
Total3 = Total2

print(f'{Total3:,}')

# Enumerate Function

names = ['Shreyas', 'Chris', 'Dev', 'Vinod']
index = 0
for name in names:
  print(index,name)
  index += 1

for index, name in enumerate(names):
  print(index,name)

# To change the start index
for index, name in enumerate(names, start = 10):
  print(index,name)

names = ['Peter Parker', 'Clark Kent', 'Wade Wilson', 'Bruce Wayne']
heros = ['Spiderman', 'Superman', 'Deadpool', 'Batman']

# usual way
for index, name in enumerate(names):
  hero = heros[index]
  print(name, 'is actually',hero)

# using Zip  functions
for name, hero in zip(names, heros):
  print(f'{name} is actually {hero}')

# use * to assign remaining values to last variable
a, b, *c = (1,2,3,4,5)
print(a)
print(b)
print(c)

# use _ to ignore remaining values
a, b, *_ = (1,2,3,4,5)
print(a)
print(b)

a, b, *c, d = (1,2,3,4,5)
print(a)
print(b)
print(c)
print(d)

a, b, *_, d = (1,2,3,4,5)
print(a)
print(b)
print(d)

username = input("Username: ")
password = input("Password: ")

print("Logging in...")

# here you can see that password is shown

from getpass import getpass

username = input("Username: ")
password = getpass("Password: ")

print("Logging in...")

# password is hidden

import re

# dir(re) # what attribute and methods are available in object
# help(re.sub)  # to get help about modules